sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database gitpay_test;' -U postgres
  - npm run migrate-test
node_js:
  - "17.3.0"

